### ISSUE TITLE
Any plan to finish this?

### ISSUE THREAD

**Issue by dthree** [grncdr/js-shell-parse#12]
Hey, this is an awesome project!

I'm considering the use of this in [Vorpal](https://github.com/dthree/vorpal) / [Cash](https://github.com/dthree/cash), however this would involve fine-tuning and perfecting its use.

I noticed you haven't committed anything in over a year. Do you have any plans on picking this project back up, or should I consider it dropped?

Thanks.

**Comment by piranna** [comment]
Hi @dthree, I was thinking about working on a fork of this project just to add the missing parts, if you want we could both work on it, how do you feel?

**Comment by dthree** [comment]
Sure! :+1:

**Comment by piranna** [comment]
Could you be able to review how to modify the grammar? I'm somewhat urgent to have support for [>|](https://github.com/grncdr/js-shell-parse/issues/10)... :-/

**Comment by piranna** [comment]
(Urgent because it's the only missing redirection, no more...)

**Comment by dthree** [comment]
I have to dive into pegjs, I've never used it (I'm sure you're at the same point). But will do so soon!

**Comment by piranna** [comment]
:+1:

**Comment by dthree** [comment]
@piranna if you could join this chat on this matter that would be great:

https://gitter.im/dthree/cash

**Comment by grncdr** [comment]
so the answer to this question is a solid "maybe, but pull-requests are very welcome, if it's not moving fast enough feel free to fork"

**Comment by grncdr** [comment]
To further clarify, since I just got an email asking what's going on.

I _didn't_ plan on finishing this, and until @parro-it mentioned me on https://github.com/sindresorhus/module-requests/issues/61 I hadn't noticed this issue. In the course of reviewing the code to bring @dthree up to speed I started cleaning up a few of the nastier parts. Then @forivall sent PR #13 with a bunch of test fixtures, and since I was already cleaning up some messy bits I thought I'd implement "just one more thing" :wink:

In any case, I **don't** think it's a great idea for the community at large to rely on me completing this library myself. There are currently 84 unparseable test cases from `shellcheck`, and probably some incorrect parses in the ones that don't fail outright, it's very unlikely I'll get that down to zero before getting busy with real-life again, so there's plenty of opportunity to contribute fixes & improvements.

I'm also serious about advising others on how to work with PEG.js & this grammar in particular. My [offer](https://github.com/sindresorhus/module-requests/issues/61#issuecomment-195468000) to @dthree is open to anybody else who's interested. I'll also gladly add anybody as a collaborator to this repo, but only _after_ they send a PR; This project has been around for over 2 years, and @forivall's is the only pull-request it's ever received.

So that's my position, I'm excited there's other people who want this finished and are willing to put in the work to make it happen. We can do it here or you can fork it and handle it how you prefer.

**Comment by dthree** [comment]
@grncdr Thanks and very appreciated!

I'm honestly not very set up to do a hangout, but if I figure that out I'll let you know!

---

I don't mind keeping the repo here and using it as a dep, it's either or to me. I was just earlier worried that you were long-gone from OSS and so we wouldn't be able to get PRs merged or something.

**Comment by grncdr** [comment]
It's probably most sensible for you to continue in your fork, I won't be spending a lot of time on this library going forward but I'll try to be available to answer questions

**Comment by dthree** [comment]
Okay thanks for all  your help!
