### ISSUE TITLE
Intentional inconsistency?

### ISSUE THREAD

**Issue by wilmoore** [grncdr/js-shell-parse#8]
I wasn't sure if this was intentional; however, I did notice some inconsistency when I have a variable assignment that includes an in-line comment:

###### actual

```
parse('DOMAIN="example.com" # with a comment')[0].type
// => 'command'
```

###### expected

```
parse('DOMAIN="example.com" # with a comment')[0].type
// => 'variableAssignment'
```

On the other hand, I get exactly what I'm expecting if I remove the comment:

```
parse('DOMAIN="example.com")[0].type
// => 'variableAssignment'
```

Not a huge deal as I can sort of work around this; however, I thought I'd mention it in case I was missing something.

**Comment by piranna** [comment]
I also get `command` when assigning the variable to nothing:

```bash
DOMAIN=
```

**Comment by grncdr** [comment]
This isn't exactly intentional, the issue is that comments aren't parsed at all right now.

@dthree this is one of the areas where peg parsing is somewhat awkward. Parsing comments _cleanly_ would require sticking the `comment` rule in the grammar everywhere a comment might appear (which is a lot of places). You could instead preprocess the input to remove all input after a `#` on each line, but then your preprocessor has to be aware of quotes & heredocs.

**Comment by piranna** [comment]
> @dthree this is one of the areas where peg parsing is somewhat awkward.
Parsing comments cleanly would require sticking the comment rule in the
grammar everywhere a comment might appear (which is a lot of places).

Not a lot of places, just before newlines... ;-)

**Comment by dthree** [comment]
@grncdr gotcha
